# Docker Composeのバージョン
version: "3.8"

# コンテナに関する定義
# コンテナ名の固定は推奨されていないため不要
services:
  mariadb:
    # container_name: mariadb   # コンテナに名前をつける
    image: mariadb:10.11   # 利用するイメージを指定
    networks:   # 接続するネットワークを指定
      - backend
    volumes:   # 記憶領域のマウントを設定
      - ./data/mariadb:/var/lib/mysql   # データの永続化（ローカルの./data/mariadbに保存）
      - ./mariadb/init:/docker-entrypoint-initdb.d:ro   # 初回起動時に実行される初期化スクリプトを置く場所へマウント
    environment:   # 環境変数を設定（環境変数は.envファイルで管理）
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    restart: unless-stopped   # コンテナが停止した時の再試行ポリシーを設定（停止していたときは再起動しない・それ以外は再起動する）

  flask:
    build: .   # カレントディレクトリ内のDockerfileからイメージを作成
    # container_name: flask
    networks:   # 接続するネットワークを指定
      - frontend
      - backend
    environment:
      FLASK_ENV: ${FLASK_ENV}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    depends_on:   # 別のサービスに依存することを示す
      - mariadb   # mariadbコンテナ起動後にflask-appコンテナ起動
    restart: unless-stopped   # コンテナが停止した時の再試行ポリシーを設定（停止していたときは再起動しない・それ以外は再起動する）

  nginx:
    # container_name: nginx   # コンテナに名前をつける
    image: nginx:1.28.0-alpine-slim   # 利用するイメージを指定
    networks:
      - frontend
    volumes:   # 記憶領域のマウントを設定
      - ./nginx/conf.d:/etc/nginx/conf.d:ro   # nginxの設定ファイルを置く場所へマウント
      - ./ssl:/etc/ssl:ro   # SSL鍵や証明書を置く場所へマウント
      - ./logs/nginx:/var/log/nginx   # ログを永続化（ローカルの./logs/nginxに保存）
    ports:   # ポートのマッピングを設定（ブラウザからのアクセス）
      - "80:80"
      - "443:443"
    depends_on:   # 別のサービスに依存することを示す
      - flask   # flaskコンテナ起動後にnginxコンテナ起動
    restart: unless-stopped   # コンテナが停止した時の再試行ポリシーを設定（停止していたときは再起動しない・それ以外は再起動する）

# ネットワークに関する定義
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge